In [72]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor

In [40]:
df1 = pd.read_csv(r"C:\Users\Dell\Documents\Final Project\Data\Sales Forecasting\features.csv")
df2 = pd.read_csv(r"C:\Users\Dell\Documents\Final Project\Data\Sales Forecasting\stores.csv")
df3 = pd.read_csv(r"C:\Users\Dell\Documents\Final Project\Data\Sales Forecasting\train.csv")
df4 = pd.merge(df1, df2, how='outer')
df = pd.merge(df4, df3, how='outer')
#df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 423325 entries, 0 to 423324
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   Store         423325 non-null  int64  
 1   Date          423325 non-null  object 
 2   Temperature   423325 non-null  float64
 3   Fuel_Price    423325 non-null  float64
 4   MarkDown1     152433 non-null  float64
 5   MarkDown2     112532 non-null  float64
 6   MarkDown3     138658 non-null  float64
 7   MarkDown4     136466 non-null  float64
 8   MarkDown5     153187 non-null  float64
 9   CPI           422740 non-null  float64
 10  Unemployment  422740 non-null  float64
 11  IsHoliday     423325 non-null  bool   
 12  Type          423325 non-null  object 
 13  Size          423325 non-null  int64  
 14  Dept          421570 non-null  float64
 15  Weekly_Sales  421570 non-null  float64
dtypes: bool(1), float64(11), int64(2), object(2)
memory usage: 52.1+ MB


In [47]:
df = df.fillna(df.mean())
df.info()

C:\Users\Dell\AppData\Local\Temp\ipykernel_18632\4027200107.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.mean())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 423325 entries, 0 to 423324
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   Store         423325 non-null  int64  
 1   Date          423325 non-null  object 
 2   Temperature   423325 non-null  float64
 3   Fuel_Price    423325 non-null  float64
 4   MarkDown1     423325 non-null  float64
 5   MarkDown2     423325 non-null  float64
 6   MarkDown3     423325 non-null  float64
 7   MarkDown4     423325 non-null  float64
 8   MarkDown5     423325 non-null  float64
 9   CPI           423325 non-null  float64
 10  Unemployment  423325 non-null  float64
 11  IsHoliday     423325 non-null  bool   
 12  Type          423325 non-null  object 
 13  Size          423325 non-null  int64  
 14  Dept          423325 non-null  float64
 15  Weekly_Sales  423325 non-null  float64
dtypes: bool(1), float64(11), int64(2), object(2)
memory usage: 52.1+ MB


In [48]:
df.head()

Store        Date  Temperature  Fuel_Price    MarkDown1    MarkDown2  \
0      1  2010-02-05        42.31       2.572  7246.604247  3337.597289   
1      1  2010-02-05        42.31       2.572  7246.604247  3337.597289   
2      1  2010-02-05        42.31       2.572  7246.604247  3337.597289   
3      1  2010-02-05        42.31       2.572  7246.604247  3337.597289   
4      1  2010-02-05        42.31       2.572  7246.604247  3337.597289   

     MarkDown3    MarkDown4    MarkDown5         CPI  Unemployment  IsHoliday  \
0  1449.098932  3382.019834  4618.743783  211.096358         8.106      False   
1  1449.098932  3382.019834  4618.743783  211.096358         8.106      False   
2  1449.098932  3382.019834  4618.743783  211.096358         8.106      False   
3  1449.098932  3382.019834  4618.743783  211.096358         8.106      False   
4  1449.098932  3382.019834  4618.743783  211.096358         8.106      False   

  Type    Size  Dept  Weekly_Sales  
0    A  151315   1.0      24924.50  
1    A  151315   2.0      50605.27  
2    A  151315   3.0      13740.12  
3    A  151315   4.0      39954.04  
4    A  151315   5.0      32229.38

In [59]:
df['Date'] = pd.to_numeric(pd.to_datetime(df['Date']))

In [61]:
#df.info()
df.head()

Store                 Date  Temperature  Fuel_Price    MarkDown1  \
0      1  1265328000000000000        42.31       2.572  7246.604247   
1      1  1265328000000000000        42.31       2.572  7246.604247   
2      1  1265328000000000000        42.31       2.572  7246.604247   
3      1  1265328000000000000        42.31       2.572  7246.604247   
4      1  1265328000000000000        42.31       2.572  7246.604247   

     MarkDown2    MarkDown3    MarkDown4    MarkDown5         CPI  \
0  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
1  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
2  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
3  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
4  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   

   Unemployment  IsHoliday Type    Size  Dept  Weekly_Sales  
0         8.106      False    A  151315   1.0      24924.50  
1         8.106      False    A  151315   2.0      50605.27  
2         8.106      False    A  151315   3.0      13740.12  
3         8.106      False    A  151315   4.0      39954.04  
4         8.106      False    A  151315   5.0      32229.38

In [62]:
df['Type'].unique()

array(['A', 'B', 'C'], dtype=object)

In [63]:
df.head()

Store                 Date  Temperature  Fuel_Price    MarkDown1  \
0      1  1265328000000000000        42.31       2.572  7246.604247   
1      1  1265328000000000000        42.31       2.572  7246.604247   
2      1  1265328000000000000        42.31       2.572  7246.604247   
3      1  1265328000000000000        42.31       2.572  7246.604247   
4      1  1265328000000000000        42.31       2.572  7246.604247   

     MarkDown2    MarkDown3    MarkDown4    MarkDown5         CPI  \
0  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
1  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
2  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
3  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
4  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   

   Unemployment  IsHoliday Type    Size  Dept  Weekly_Sales  
0         8.106      False    A  151315   1.0      24924.50  
1         8.106      False    A  151315   2.0      50605.27  
2         8.106      False    A  151315   3.0      13740.12  
3         8.106      False    A  151315   4.0      39954.04  
4         8.106      False    A  151315   5.0      32229.38

In [64]:
df5 = df.replace({'Type':{'A':0,'B':1,'C':2}})

In [65]:
df5.head()

Store                 Date  Temperature  Fuel_Price    MarkDown1  \
0      1  1265328000000000000        42.31       2.572  7246.604247   
1      1  1265328000000000000        42.31       2.572  7246.604247   
2      1  1265328000000000000        42.31       2.572  7246.604247   
3      1  1265328000000000000        42.31       2.572  7246.604247   
4      1  1265328000000000000        42.31       2.572  7246.604247   

     MarkDown2    MarkDown3    MarkDown4    MarkDown5         CPI  \
0  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
1  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
2  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
3  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   
4  3337.597289  1449.098932  3382.019834  4618.743783  211.096358   

   Unemployment  IsHoliday  Type    Size  Dept  Weekly_Sales  
0         8.106      False     0  151315   1.0      24924.50  
1         8.106      False     0  151315   2.0      50605.27  
2         8.106      False     0  151315   3.0      13740.12  
3         8.106      False     0  151315   4.0      39954.04  
4         8.106      False     0  151315   5.0      32229.38

In [66]:
df5.corr()

Store      Date  Temperature  Fuel_Price  MarkDown1  \
Store         1.000000  0.003884    -0.050010    0.065511  -0.071714   
Date          0.003884  1.000000     0.143278    0.767826  -0.004331   
Temperature  -0.050010  0.143278     1.000000    0.142966  -0.024550   
Fuel_Price    0.065511  0.767826     0.142966    1.000000   0.023259   
MarkDown1    -0.071714 -0.004331    -0.024550    0.023259   1.000000   
MarkDown2    -0.017571 -0.055035    -0.163477   -0.070229   0.022572   
MarkDown3    -0.017966 -0.043851    -0.052118   -0.036234  -0.105152   
MarkDown4    -0.005253 -0.011975    -0.034654   -0.015481   0.785129   
MarkDown5    -0.015110 -0.017212    -0.009235   -0.045519   0.153133   
CPI          -0.210898  0.076986     0.181678   -0.164412  -0.033973   
Unemployment  0.208291 -0.243837     0.097698   -0.033895   0.027340   
IsHoliday    -0.000539 -0.012946    -0.156080   -0.078261  -0.019090   
Type          0.226640  0.004908     0.042942    0.029766  -0.153982   
Size         -0.183170 -0.006321    -0.058354    0.003284   0.207038   
Dept          0.023952  0.004014     0.004426    0.003568  -0.001443   
Weekly_Sales -0.085012 -0.000656    -0.002307   -0.000120   0.051728   

              MarkDown2  MarkDown3  MarkDown4  MarkDown5       CPI  \
Store         -0.017571  -0.017966  -0.005253  -0.015110 -0.210898   
Date          -0.055035  -0.043851  -0.011975  -0.017212  0.076986   
Temperature   -0.163477  -0.052118  -0.034654  -0.009235  0.181678   
Fuel_Price    -0.070229  -0.036234  -0.015481  -0.045519 -0.164412   
MarkDown1      0.022572  -0.105152   0.785129   0.153133 -0.033973   
MarkDown2      1.000000  -0.047653  -0.007567  -0.007007 -0.020765   
MarkDown3     -0.047653   1.000000  -0.069385  -0.024214 -0.013709   
MarkDown4     -0.007567  -0.069385   1.000000   0.100112 -0.028669   
MarkDown5     -0.007007  -0.024214   0.100112   1.000000  0.034982   
CPI           -0.020765  -0.013709  -0.028669   0.034982  1.000000   
Unemployment   0.009470   0.006402   0.012952  -0.001132 -0.300008   
IsHoliday      0.198596   0.265271   0.001924  -0.032524 -0.001869   
Type          -0.030535  -0.021063  -0.051205  -0.149032 -0.065691   
Size           0.052365   0.027183   0.085195   0.175357 -0.003377   
Dept           0.000147   0.001003   0.002367   0.000068 -0.007466   
Weekly_Sales   0.013058   0.035604   0.026779   0.052496 -0.020888   

              Unemployment  IsHoliday      Type      Size      Dept  \
Store             0.208291  -0.000539  0.226640 -0.183170  0.023952   
Date             -0.243837  -0.012946  0.004908 -0.006321  0.004014   
Temperature       0.097698  -0.156080  0.042942 -0.058354  0.004426   
Fuel_Price       -0.033895  -0.078261  0.029766  0.003284  0.003568   
MarkDown1         0.027340  -0.019090 -0.153982  0.207038 -0.001443   
MarkDown2         0.009470   0.198596 -0.030535  0.052365  0.000147   
MarkDown3         0.006402   0.265271 -0.021063  0.027183  0.001003   
MarkDown4         0.012952   0.001924 -0.051205  0.085195  0.002367   
MarkDown5        -0.001132  -0.032524 -0.149032  0.175357  0.000068   
CPI              -0.300008  -0.001869 -0.065691 -0.003377 -0.007466   
Unemployment      1.000000   0.010172  0.148305 -0.067831  0.007825   
IsHoliday         0.010172   1.000000 -0.000786  0.000579  0.000914   
Type              0.148305  -0.000786  1.000000 -0.811481  0.003700   
Size             -0.067831   0.000579 -0.811481  1.000000 -0.002960   
Dept              0.007825   0.000914  0.003700 -0.002960  1.000000   
Weekly_Sales     -0.025826   0.012745 -0.181818  0.243281  0.148032   

              Weekly_Sales  
Store            -0.085012  
Date             -0.000656  
Temperature      -0.002307  
Fuel_Price       -0.000120  
MarkDown1         0.051728  
MarkDown2         0.013058  
MarkDown3         0.035604  
MarkDown4         0.026779  
MarkDown5         0.052496  
CPI              -0.020888  
Unemployment     -0.025826  
IsHoliday         0.012745  
Type            

In [67]:
x = df5.iloc[:,0:-1].values
y = df5.iloc[:,-1:].values

In [68]:
print(x)
print(y)

[[1 1265328000000000000 42.31 ... 0 151315 1.0]
 [1 1265328000000000000 42.31 ... 0 151315 2.0]
 [1 1265328000000000000 42.31 ... 0 151315 3.0]
 ...
 [45 1373587200000000000 79.37 ... 1 118221 44.26031738501317]
 [45 1374192000000000000 82.84 ... 1 118221 44.26031738501317]
 [45 1374796800000000000 76.06 ... 1 118221 44.26031738501317]]
[[24924.5       ]
 [50605.27      ]
 [13740.12      ]
 ...
 [15981.25812347]
 [15981.25812347]
 [15981.25812347]]


In [69]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [70]:
dt_regressor = DecisionTreeRegressor()
dt_regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [71]:
y_pred_dt = dt_regressor.predict(x_test)

In [74]:
print(r2_score(y_test, y_pred_dt))

0.9146139660086827
